# Generated by Django 4.2.3 on 2023-07-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_article_category_alter_result_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleCategory',
        ),
        migrations.RenameModel(
            old_name='Article_category',
            new_name='BlogPostCategory',
        ),
        migrations.RenameModel(
            old_name='Question_category',
            new_name='QuestionCategory',
        ),
        migrations.RenameModel(
            old_name='Blog_post',
            new_name='BlogPost',
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='blog')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='blog')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.article')),
            ],
        ),
    ]
